export const GET_DATA_API = "GET_DATA_API"
export const GET_DATA_API_SUCCESS = "GET_DATA_API_SUCCESS"
export const GET_DATA_API_FAILED = "GET_DATA_API_FAILED"


export const GET_DATA_FOLLOW_API = "GET_DATA_FOLLOW_API"
export const GET_DATA_FOLLOW_API_SUCCESS = "GET_DATA_FOLLOW_API_SUCCESS"
export const GET_DATA_FOLLOW_API_FAILED = "GET_DATA_FOLLOW_API_FAILED"
